apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hlac2ve1p-python 
  janus-idp.io/tekton: hlac2ve1p-python
  backstage.io/kubernetes-id: hlac2ve1p-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hlac2ve1p-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  